### ISSUE TITLE
How control when a process ends?

### ISSUE THREAD

**Issue by rhedin** [sdedit/sdedit#1]
Hi, Markus.  Used your stuff very effectively today at work.  Thanks!

I ended up sending all my messages asynchronously.  I wasn't sure how to control when a process ended, if there were several other interactions before the original message was satisfied.  Can you explain how the layers of message interactions work?  How do they know when the layer is complete?  Does it count messages out and message in and make sure they balance?

**Comment by sdedit** [comment]
Have you read the built-in documentation first? Is there anything that is not clear to you? If so, please refer to the things that remain unclear and ask again.
