### ISSUE TITLE
Does the NodeJS wrapper for sdedit honor the license?

### ISSUE THREAD

**Issue by nicojs** [sdedit/sdedit#14]
Thanks for creating sdedit. I use it a lot and it works great! I've created a small nodejs wrapper to use sdedit in a nodejs build (for example with grunt). You can look it up here: https://npmjs.org/package/sdedit

I'm not a license expert. Did i honor the BSD 2 license? The package itself is licensed as Apache-2.0 and i put the original author's name in the readme and help text.

**Comment by sdedit** [comment]
I guess you have made it right. No need to worry.
