### ISSUE TITLE
Arrow type for answer message

### ISSUE THREAD

**Issue by cnt5bs** [sdedit/sdedit#2]
Hi Strauch. Your **sdedit** is wonderful. I modified the answer message head type (UML2) in `sdedit::drawable::Arrow::Arrow()` for my students as

```
if (stroke != ArrowStroke.NONE) {
    headSize = diagram().arrowSize;
    // Italo
    if (stroke == ArrowStroke.DASHED) {  
        headType = ArrowHeadType.OPEN; // <- I need this
    } else {
        headType = message instanceof BroadcastMessage ? ArrowHeadType.ROUNDED
            : message.isSynchronous() ? ArrowHeadType.CLOSED : ArrowHeadType.OPEN;
    }
} else { ...
```

Best regards.

**Comment by sdedit** [comment]
This is not an issue. I am not sure if I should include your change. Can you explain why it is a good thing to have an open arrow head there?

**Comment by cnt5bs** [comment]
Hi Strauch. I need this because the students follow the "Sequence Diagram Notation" showed in "Table 17.2 Graphic Paths Included in Sequence Diagrams", p. 596, OMG Unified Modeling Language 2.5.
Thank you again.
