### ISSUE TITLE
incompatible version of QSD-lib (have 4.2.4; QSD wanted 4.2.3)

### ISSUE THREAD

**Issue by dhlocker** [sdedit/sdedit#8]
"[ERROR] Failed to execute goal on project QSD: Could not resolve dependencies for project net.sf.sdedit:QSD:jar:4.2: Failure to find net.sf.sdedit:QSD-lib:jar:4.2.3 in file:///C:\Users\dlocker\AppData\Roaming\local\bin\sdedit-master\QSD/repo was cached in the local repository, resolution will not be reattempted until the update interval of repo has elapsed or updates are forced -> [Help 1]"

Looks like QSD-lib is version 4.2.4; QSD is looking for 4.2.3;
changed QSD/pom.xml <dependency> for net.sf.sdedit/QSD-lib from <version>4.2.3 to 4.2.4 and build completed normally.

**Comment by sdedit** [comment]
I've finally updated the pom.xml.
