### ISSUE TITLE
Does QSD support text formatting?

### ISSUE THREAD

**Issue by school510587** [sdedit/sdedit#9]
When demonstrating a protocol using a sequence diagram, it is often needed to add superscript or subscript text to make terms more clear and understandable.
I read "How to enter text" specification of QSD, but nothing found about this.
If QSD has already support these effects, could you tell me where the corresponding specification is?
Otherwise, if possible, I hope QSD will support text formatting such as superscripting, subscripting, font size/color, etc.
Thanks for any response.

**Comment by sdedit** [comment]
Text formatting is currently not supported, but might be realized in a new version, using Java's built-in (somewhat limited and out-dated) HTML rendering capabilities. This would imply that, for example, to add a subscript to a message you'd have to write a small piece of HTML, like `H<sub>2</sub>O`, to get H<sub>2</sub>O.

**Comment by school510587** [comment]
OK, thanks. I also know some useful applications require HTML syntax to format the text, and look forward to your new version.

**Comment by sdedit** [comment]
Get the new version here: https://github.com/sdedit/sdedit/releases/tag/v4.2-beta9 and tell me if it works for you, please. As far as I see, HTML rendering does not work very well when a diagram is zoomed. Whitespace before text that has markup might become larger than it should be, underlines might be longer than necessary.

**Comment by school510587** [comment]
Thank you very much. However, where should I get an instruction or examples of syntax generating sequence diagrams with formatted text?
I don't mean a tutorial of writing HTML. Generally, some special marks will be present if the user wants some text is treated as HTML (or XML, other syntax).
I wonder if there is any difference of syntax to write messages in plaintext format and in HTML.

**Comment by sdedit** [comment]
You can add HTML markup almost everywhere you enter text that gets drawn on the diagram. It is not advisable for object names.

For example

`a:<b>Teacher</b>`
`b:<small>Pupil</small>`

`a:C<sub>6</sub>H<sub>6</sub>=b.Chemical formula of <i>benzene</i>?`

**Comment by school510587** [comment]
I also test the new version (beta9) and find HTML-style syntax basically works.
May all of known problems you listed above be solved before the next stable (not beta) release. Thanks.

**Comment by sdedit** [comment]
Sorry, but these problems are due to Java Swing's poor HTML rendering. Neither can I nor want I to solve them.

**Comment by school510587** [comment]
That's ok. Then I believe Java will improve it one day.

**Comment by sdedit** [comment]
I do not think that this will happen. JavaFX provides much better HTML rendering, making obsolete what Swing offers. So sdedit should be ported from Swing to JavaFX, shouldn't it?

**Comment by school510587** [comment]
Sorry, I don't have profound knowledge about Swing and JavaFX. However, I think it's great to use better packages to improve sdedit.
